# Here we define various settings for different items, one item at a time
Items:
  # Each item has a fixed set of properties with pre-defined default values

  # Name
  # The name of an item we want to configure
  - name: "Chaos Orb"
    # Minimum Stock
    # This defines the minimum stock a trade offer has to have to be considered.
    # If an offer permits less than this thres
    minimum_stock: 1
    # Maximum Stock
    # This defines how
    maximum_stock: 0
    trades_into:
      - "*"
  - name: "Exalted Orb"
    minimum_stock: 1
    maximum_stock: 0
    trades_into:
      - "*"
  - name: "Orb of Fusing"
    minimum_stock: 1
    maximum_stock: 0
    trades_into:
      - "*"
